# Generated by Django 4.2.3 on 2023-07-28 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.BooleanField(default=False)),
                ('edit_user', models.BooleanField(default=False)),
                ('delete_user', models.BooleanField(default=False)),
                ('create_project', models.BooleanField(default=False)),
                ('assess_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dycode.module')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dycode.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dycode.user')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dycode.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'create'), ('U', 'update'), ('D', 'delete'), ('R', 'restore')], max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='dycode.user')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyect', to='dycode.user'),
        ),
    ]
