# Generated by Django 4.2.3 on 2023-07-22 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.BooleanField(default=False)),
                ('edit_user', models.BooleanField(default=False)),
                ('delete_user', models.BooleanField(default=False)),
                ('create_project', models.BooleanField(default=False)),
                ('assess_project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, unique=True)),
                ('module', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dycode.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='acceso',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='archivo',
            new_name='field',
        ),
        migrations.DeleteModel(
            name='Estudiante_Eliminado',
        ),
        migrations.DeleteModel(
            name='Nivel_Acceso',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='participantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dycode.user'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
