# Generated by Django 4.2.3 on 2023-07-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dycode.module'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
