# Generated by Django 4.2.3 on 2023-07-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
