# Generated by Django 4.2.3 on 2023-07-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0005_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
