# Generated by Django 4.2.3 on 2023-07-30 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0006_remove_user_last_login_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrespaldo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
