# Generated by Django 4.2.3 on 2023-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dycode', '0007_userrespaldo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='field',
            field=models.CharField(max_length=250),
        ),
    ]
